### ISSUE TITLE
suggestions for openpnp instructions

### ISSUE THREAD

**Issue by securelyfitz** [opulo-inc/docs#99]
In general the instructions are great - however the get very tedious and repetitive when they go through the whole process, with screenshots, of navigating to different settings. After we've done it once or twice, it would be more helpful to abbreviate it - for example:
```
Tuning the homing fiducial
1. Navigate to Machine setup-> ReferenceHead H1-> Configuration
```
... and jumping straight to the screenshot in step 4

Some other details i came across:

- connect step 6: on linux you'll need to join the dialout and video groups, or provide udev rules for the lumen's usb devices
- connecting step 6: i struggled for a while before i realized there were lens caps on both cameras! Maybe add removing them to the instructions
- fisheye calibration: this topic doesn't show up in the menu pane, and the previous/next links on connecting and homing don't jump to it. The homing instructions do reference it: "Now that fisheye calibration is complete, we can set up the datum board", and the page does exist if you directly link to it.
- MM/Pixel - mention removing the set screw before trying to focus the camera
- Nozzle offset step 1: this is the first mention of installing a nozzle, but it's the *only* time you don't mention using lubricant
- Setting up the Board step 1: it's not possible as described due to the placement of the pumps under the board. the note does say that you can do it elsewhere - but it also says it's easier to do it where it says.

**Comment by gabeseltzer** [comment]
Thanks for the comments! I've addressed them in the PR. Some were already done, like the lens caps bit in #100 .  We got rid of fisheye calibration, as it's done during assembly of new LumenPnPs, so I've removed that reference, thanks. And for setting up the board, I think I already corrected that from another comment since yours has been made.

Thanks for the feedback! Please add more if you find stuff that needs fixing.
